npm-init:
	npm init
npm-express:
	npm install express
npm-dotenv:
	npm install dotenv
npm-mongodb:
	npm install --save mongodb
npm-cors:
	npm install cors
npm-joi:
	npm i joi
npm-bcrypt:
	npm i bcrypt
npm-umzug:
	npm install umzug
npm-jsonwebtoken:
	npm install jsonwebtoken
npm-cookie-parser:
	npm i cookie-parser
npm-multer:
	npm i multer
npm-cloudinary:
	npm i cloudinary
start-app:
	npm run start
migrate-up:
	node migrate.js