npm-init:
	npm init
npm-express:
	npm install express
npm-dotenv:
	npm install dotenv
npm-mongodb:
	npm install --save mongodb
npm-cors:
	npm install cors
npm-joi:
	npm i joi
npm-bcrypt:
	npm i bcrypt
npm-umzug:
	npm install umzug
start-app:
	npm run start

# for migration mongodb
migrate-up:
	node migrate.js